apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    cluster: master
    appType: app-of-apps
  name: master-applications
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - shared-values.yaml
        - master-values.yaml
      parameters:
        - name: global.domain
          value: "글로벌 도메인을 입력하세요 ex) testdomain.com"
        - name: global.masterSingle.hyperAuthDomain
          value: "hyperauth full 도메인을 입력하세요 ex) hyperauth.testdomain.com"
        # Avaliable values: UTC, Asia/Seoul
        - name: global.timeZone
          value: "UTC"
        # Quote is essential
        - name: global.network.disabled
          value: "true"
          forceString: true
        - name: global.privateRegistry
          value: "폐쇄망일 경우 image registry 주소를 입력하세요 ex) https://hyperregistry.testdomain.com"
        - name: spec.source.repoURL
          value: "git repository URL을 입력하세요 ex) https://github.com/tmax-cloud/argocd-installer.git"
        - name: spec.source.targetRevision
          value: "target Revision을 입력하세요 ex) main"
    path: application/helm
    # 환경에 맞게 url 주소 변경 필요
    repoURL: https://github.com/tmax-cloud/argocd-installer
    # 환경에 맞게 target branch/release 변경 필요
    targetRevision: HEAD
