apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-config
  labels:
    app: sonarqube
data:
  sonar.properties: |
    sonar.core.serverBaseURL = {{ .Values.sonarProperties.oidc.serverBaseURL }}
    sonar.auth.oidc.clientId.secured = {{ .Values.sonarProperties.oidc.clientId }}
    sonar.auth.oidc.clientSecret.secured = {{ .Values.sonarProperties.oidc.clientSecret }}
    sonar.auth.oidc.enabled = {{ .Values.sonarProperties.oidc.enabled }}
    sonar.auth.oidc.issuerUri = {{ .Values.sonarProperties.oidc.issuerUri }}